# Imported for boot-activated IPE or explicit manual configuration.
version = 3

[plugins."io.containerd.snapshotter.v1.erofs"]
  enable_dmverity_referrers = true

[plugins."io.containerd.cri.v1.images"]
  snapshotter = "erofs"

[plugins."io.containerd.service.v1.diff-service"]
  default = ["erofs", "walking"]
