#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# sign_uki_ephemeral.sh — Sign the UKI Secure Boot chain with an ephemeral
# (self-signed) key. Covers both systemd-boot (EFI/BOOT/grub*.efi, shim's
# second stage) and the UKI + addons (EFI/Linux/*.efi, acl/uki-addons/*).
# Shim itself (EFI/BOOT/BOOT<ARCH>.EFI) is Microsoft-signed and left alone.
#
# This script generates a one-time RSA 2048-bit certificate and signs all
# applicable EFI binaries on the mounted ESP. The public certificate
# (ca.pem) is written to the output directory so it can be enrolled in:
#   - OVMF Secure Boot db  (for QEMU testing via virt-fw-vars)
#   - Azure gallery image  (for Azure VM testing via securityProfile)
#
# The private key is deleted after signing.
#
# Usage:
#   sign_uki_ephemeral.sh <esp-mount-dir> <cert-output-dir>
#
# Requirements (all available in the SDK container):
#   - openssl   (key and certificate generation)
#   - sbsign    (EFI Authenticode signing — from app-crypt/sbsigntools)

set -euo pipefail

ESP_DIR="${1:?Usage: sign_uki_ephemeral.sh <esp-mount-dir> <cert-output-dir> [ipe-policy-src]}"
CERT_OUTPUT_DIR="${2:?Usage: sign_uki_ephemeral.sh <esp-mount-dir> <cert-output-dir> [ipe-policy-src]}"
# Optional: when given, also sign the ACL IPE policy with the SAME ephemeral
# key and place it on the ESP (see the block after EFI signing).
IPE_POLICY_SRC="${3:-}"
# Optional (arg 4): directory holding the per-build ephemeral cert already
# generated by uki_install.sh to sign the /usr verity roothash. When set, reuse
# that exact cert/key here so the single enrolled db cert verifies the UKI, the
# IPE policy, AND the verity roothash signature.
EPHEMERAL_CERT_DIR="${4:-}"

CERT_NAME="uki-signing-ca.pem"

info()  { echo "[sign_uki_ephemeral] $*"; }
error() { echo "[sign_uki_ephemeral] ERROR: $*" >&2; }

sign_efi_file() {
    local efi_file="$1"
    local local_name
    local signed_tmp

    local_name=$(basename "${efi_file}")
    info "  Signing: ${local_name}"

    signed_tmp="${WORK_DIR}/${local_name}.signed"

    sbsign \
        --key "${KEY_FILE}" \
        --cert "${CERT_FILE}" \
        --output "${signed_tmp}" \
        "${efi_file}"

    sudo mv "${signed_tmp}" "${efi_file}"
}

if [[ ! -d "${ESP_DIR}" ]]; then
    error "ESP directory does not exist: ${ESP_DIR}"
    exit 1
fi

if [[ ! -d "${ESP_DIR}/EFI/Linux" ]]; then
    error "No EFI/Linux directory on ESP — is this a UKI image?"
    exit 1
fi

mkdir -p "${CERT_OUTPUT_DIR}"

# Scratch dir for intermediate signing artifacts (always needed by sign_efi_file
# and the IPE policy signing below).
WORK_DIR=$(mktemp -d)
trap 'rm -rf "${WORK_DIR}"' EXIT

CERT_FILE="${CERT_OUTPUT_DIR}/${CERT_NAME}"

if [[ -n "${EPHEMERAL_CERT_DIR}" ]]; then
    # Reuse the per-build ephemeral cert that uki_install.sh already generated to
    # sign the /usr verity roothash. The SAME cert must sign the UKI + IPE policy
    # and be the one enrolled in the VM db; otherwise the roothash signature will
    # not verify against .platform and /usr verity setup fails (unbootable). If
    # it is missing, fail loudly rather than enroll a mismatched cert.
    if [[ ! -s "${EPHEMERAL_CERT_DIR}/ca.key" || ! -s "${EPHEMERAL_CERT_DIR}/${CERT_NAME}" ]]; then
        error "Shared ephemeral cert not found in ${EPHEMERAL_CERT_DIR} (expected from uki_install.sh)"
        exit 1
    fi
    KEY_FILE="${EPHEMERAL_CERT_DIR}/ca.key"
    cp -f "${EPHEMERAL_CERT_DIR}/${CERT_NAME}" "${CERT_FILE}"
    info "Reusing shared per-build ephemeral cert (also signs the /usr verity roothash)"
else
    # No shared cert (non-IPE build): generate a standalone throwaway cert.
    KEY_FILE="${WORK_DIR}/ca.key"
    info "Generating ephemeral signing certificate..."
    openssl req -x509 \
        -newkey rsa:2048 \
        -days 1 \
        -noenc \
        -keyout "${KEY_FILE}" \
        -out "${CERT_FILE}" \
        -subj "/CN=ACL Ephemeral Signing $(date +%Y%m%d%H%M%S)" \
        -sha256 \
        -addext "basicConstraints=CA:FALSE" \
        -addext "extendedKeyUsage=codeSigning" \
        2>&1
fi

info "Certificate: ${CERT_FILE}"

# Sign every EFI binary on the ESP that shim or the firmware will verify
# against UEFI db. The Secure Boot chain is:
#   firmware → EFI/BOOT/BOOT<ARCH>.EFI (shim, Microsoft-signed — DO NOT re-sign)
#           → EFI/BOOT/grub<ARCH>.efi  (systemd-boot, normally Mariner-signed;
#                                       unsigned when RPMs come from a dev
#                                       pipeline → sign with ephemeral key)
#           → EFI/Linux/<uki>.efi      (UKI + addons — sign with ephemeral key)
#           → acl/uki-addons/*.efi     (addon templates, signed for runtime use)
# Active and template copies are independent files, so each is signed directly.
# The ephemeral CA cert is enrolled in the gallery image's Secure Boot db by
# publish_to_gallery.sh, so shim accepts the signatures produced here.
declare -a efi_files=()

while IFS= read -r -d '' efi_file; do
    efi_files+=("${efi_file}")
done < <(
    find \
        "${ESP_DIR}/EFI/Linux" \
        "${ESP_DIR}/acl/uki-addons" \
        -name '*.efi' -type f -print0 2>/dev/null
    # systemd-boot is installed as grub<arch>.efi (shim looks it up by that
    # name). Match grub*.efi explicitly and skip BOOT<ARCH>.EFI (shim itself).
    find \
        "${ESP_DIR}/EFI/BOOT" \
        -maxdepth 1 -type f -iname 'grub*.efi' -print0 2>/dev/null
)

if [[ ${#efi_files[@]} -eq 0 ]]; then
    error "No EFI files found to sign"
    exit 1
fi

info "Found ${#efi_files[@]} EFI file(s) to sign"

for efi_file in "${efi_files[@]}"; do
    sign_efi_file "${efi_file}"
done

# Private key is in WORK_DIR which is cleaned up by the trap.
info "Signing complete. ${#efi_files[@]} file(s) signed."
info "Public certificate: ${CERT_FILE}"

# Optionally sign the ACL IPE policy with the SAME ephemeral key, while it
# still exists (WORK_DIR is removed by the EXIT trap). Because CERT_FILE is the
# same cert enrolled in the Secure Boot db, the kernel's .platform keyring will
# trust this policy's signature at load time -- no separate enrollment needed.
# The rootfs is read-only at image_to_vm time, so the signed policy is placed on
# the ESP (writable here; mounted rw at /boot at runtime). The kernel verifies
# the policy's PKCS#7 signature against .platform regardless of where the file
# lives, so the writable ESP is safe. acl-ipe-load.service reads it from /boot.
if [[ -n "${IPE_POLICY_SRC}" ]]; then
    if [[ ! -f "${IPE_POLICY_SRC}" ]]; then
        error "IPE policy source not found: ${IPE_POLICY_SRC}"
        exit 1
    fi
    info "Signing IPE policy ${IPE_POLICY_SRC} with ephemeral key"
    ipe_out_dir="${ESP_DIR}/acl-ipe"
    ipe_p7b_tmp="${WORK_DIR}/acl.pol.p7b"
    openssl smime -sign \
        -in "${IPE_POLICY_SRC}" \
        -signer "${CERT_FILE}" \
        -inkey "${KEY_FILE}" \
        -noattr -nodetach -nosmimecap \
        -outform der \
        -out "${ipe_p7b_tmp}"
    sudo mkdir -p "${ipe_out_dir}"
    sudo cp "${ipe_p7b_tmp}" "${ipe_out_dir}/acl.pol.p7b"
    info "IPE policy signed -> ${ipe_out_dir}/acl.pol.p7b (ESP)"
fi
