#!/bin/bash
#
# Validate the golden document against SPDX 2.2.
#
# Deliberately not in CI because it requires third-party Python packages, and
# test_generate_package_manifest.sh, which is in CI, already validates that the
# generator reproduces the golden document byte for byte. This, however, says
# nothing about whether that document is a valid one, so this script is run
# whenever it is regenerated.
#
# Usage: validate_golden_manifest.sh [workdir]

set -euo pipefail

TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFORMANCE="${TESTS_DIR}/test_generate_package_manifest.sh"

REQUIREMENTS="${TESTS_DIR}/requirements.txt"

if [[ $# -ge 1 ]]; then
    WORK_DIR="${1}"
else
    WORK_DIR="$(mktemp -d)"
    trap 'rm -rf "${WORK_DIR}"' EXIT
fi
mkdir -p "${WORK_DIR}"

# Validating the generated document rather than the golden file itself, because
# the golden is generated by the repository tool and so is not
# the shape that ships. This also fails first if the two have diverged.
"${CONFORMANCE}" "${WORK_DIR}"

MANIFEST="${WORK_DIR}/package-manifest.spdx.json"
VENV="${WORK_DIR}/.venv"

echo "=== Provisioning validators ==="
python3 -m venv "${VENV}"
"${VENV}/bin/pip" install \
    --quiet \
    --disable-pip-version-check \
    --requirement "${REQUIREMENTS}"

# pyspdxtools prints the individual validation messages.
echo "=== SPDX 2.2 validation ==="
"${VENV}/bin/pyspdxtools" --infile="${MANIFEST}"

echo "=== PASS ==="
