#!/bin/bash
# Publish the active ACL A/B slot ("volume") marker as early as possible.
#
# The active /usr slot is derived purely from the kernel command line, which
# systemd-stub has already assembled from the signed UKI plus any signed
# addons by the time PID 1 starts.  Because this needs nothing but
# /proc/cmdline, it can run before udev, before any block device has been
# probed, and before /sysroot is mounted.
#
# The slot identity comes from `systemd.verity_usr_data=PARTUUID=...`, which
# names the USR partition the running system booted from (see
# build_library/rpm/uki_install.sh).  Non-verity images carry the equivalent
# `mount.usr=PARTUUID=...` instead, which is used as a fallback.  The USR-A
# and USR-B PARTUUIDs are build-time constants pinned in
# build_library/disk_layout_uki.json.
#
# Outputs (both under /run, which switch-root moves into the real root, so
# they remain readable by real-root services):
#
#   /run/acl/active-volume      Always written. Contains exactly "A" or "B"
#                               plus a newline.
#   /run/acl/active-volume.env  Always written.  EnvironmentFile-compatible.
#
# When the slot cannot be derived, this falls back to "A": ACL images are
# built with USR-A prioritized and with the USR-A PARTUUID baked into the UKI
# cmdline, so A is the correct answer for every image that has not been
# through an A/B switch.  The fallback is recorded in
# ACL_ACTIVE_VOLUME_DEFAULTED so that a consumer needing certainty can tell
# a derived answer from a defaulted one.
#
# This script never fails a boot: every path exits 0.

set -uo pipefail

# PARTUUIDs of the USR-A / USR-B partitions, from disk_layout_uki.json.
# These are fixed constants of the ACL disk layout and are deliberately not
# resolved via udev, so that this can run before device enumeration.
readonly USR_A_PARTUUID="7130c94a-213a-4e5a-8e26-6cce9662f132"
readonly USR_B_PARTUUID="e03dd35c-7c2d-4a47-b3fe-27f15780a57c"

readonly RUN_DIR="/run/acl"
readonly MARKER_FILE="${RUN_DIR}/active-volume"
readonly ENV_FILE="${RUN_DIR}/active-volume.env"

log() { echo "acl-active-volume: $*" >&2; }

# Write a file atomically so a concurrent reader never observes a partial file.
write_atomic() {
    local dest="$1" tmp
    tmp="${dest}.tmp.$$"
    if cat > "${tmp}"; then
        mv -f "${tmp}" "${dest}" && return 0
    fi
    rm -f "${tmp}"
    return 1
}

cmdline=""
if ! read -r cmdline < /proc/cmdline; then
    log "WARNING: unable to read /proc/cmdline"
fi

# Split on whitespace, with globbing disabled so that a cmdline containing
# shell wildcards cannot expand against the filesystem.
verity_usr_data=""
mount_usr=""
set -f
for arg in ${cmdline}; do
    case "${arg}" in
        systemd.verity_usr_data=PARTUUID=*)
            verity_usr_data="${arg#systemd.verity_usr_data=PARTUUID=}"
            ;;
        mount.usr=PARTUUID=*)
            mount_usr="${arg#mount.usr=PARTUUID=}"
            ;;
    esac
done
set +f

# Prefer the verity data partition: on verity images it is authoritative, and
# unlike systemd.verity_usr_hash= it still names the USR partition once
# dedicated hash partitions exist.
if [[ -n "${verity_usr_data}" ]]; then
    partuuid="${verity_usr_data,,}"
    source_arg="systemd.verity_usr_data"
else
    partuuid="${mount_usr,,}"
    source_arg="mount.usr"
fi

volume=""
usr_label=""
status=""
defaulted=0

case "${partuuid}" in
    "")
        status="no-usr-partuuid-on-cmdline"
        source_arg="default"
        defaulted=1
        ;;
    "${USR_A_PARTUUID}")
        volume="A"
        usr_label="USR-A"
        status="ok"
        ;;
    "${USR_B_PARTUUID}")
        volume="B"
        usr_label="USR-B"
        status="ok"
        ;;
    *)
        log "WARNING: PARTUUID ${partuuid} from ${source_arg} matches neither USR-A nor USR-B"
        status="unrecognized-usr-partuuid"
        source_arg="default"
        defaulted=1
        ;;
esac

# Fall back to slot A. ACL images prioritize USR-A (disk_layout_uki.json) and
# bake its PARTUUID into the UKI cmdline, so A is correct for any image that
# has not been through an A/B switch.
if (( defaulted )); then
    volume="A"
    usr_label="USR-A"
    partuuid="${USR_A_PARTUUID}"
fi

umask 022
if ! mkdir -p "${RUN_DIR}"; then
    log "ERROR: unable to create ${RUN_DIR}, not publishing marker"
    exit 0
fi

if ! write_atomic "${ENV_FILE}" <<EOF
# Generated by acl-active-volume. Do not edit.
ACL_ACTIVE_VOLUME=${volume}
ACL_ACTIVE_USR_LABEL=${usr_label}
ACL_ACTIVE_USR_PARTUUID=${partuuid}
ACL_ACTIVE_VOLUME_SOURCE=${source_arg}
ACL_ACTIVE_VOLUME_STATUS=${status}
ACL_ACTIVE_VOLUME_DEFAULTED=${defaulted}
EOF
then
    log "ERROR: unable to write ${ENV_FILE}"
fi

if printf '%s\n' "${volume}" | write_atomic "${MARKER_FILE}"; then
    if (( defaulted )); then
        log "active volume defaulted to ${volume} (${status})"
    else
        log "active volume ${volume} (${usr_label}, PARTUUID=${partuuid}) via ${source_arg}"
    fi
else
    log "ERROR: unable to write ${MARKER_FILE}"
fi

exit 0
